"""Golden-vector tests for the BB-8 codec.

These vectors are the contract between the Python CLI and the Swift port. Both
implementations must produce byte-identical output for the same inputs, so this
file is exported as the shared test corpus in step 2 (see docs/06 §3).

Vectors are hand-computed from the Sphero API 1.20 frame layout, deliberately not
generated by calling the code under test -- a vector produced by the implementation
proves only self-consistency.
"""

import pytest

from bb8ctl import protocol as p


class TestChecksum:
    def test_known_value(self):
        # 0xFF - (sum & 0xFF); sum(02,01,00,03,00,00) = 0x06 -> 0xF9
        assert p.checksum(bytes([0x02, 0x01, 0x00, 0x03, 0x00, 0x00])) == 0xF9

    def test_wraps_modulo_256(self):
        assert p.checksum(bytes([0xFF, 0xFF])) == 0xFF - 0xFE

    def test_empty_payload(self):
        assert p.checksum(b"") == 0xFF

    def test_always_a_byte(self):
        for n in range(0, 256):
            assert 0 <= p.checksum(bytes([n] * 7)) <= 0xFF


class TestFraming:
    def test_layout_is_sop_sop_did_cid_seq_dlen_data_chk(self):
        pkt = p.build(0x02, 0x30, seq=0x05, data=bytes([0x64, 0x00, 0x5A, 0x01, 0x00]))
        assert pkt[0] == 0xFF          # SOP1
        assert pkt[1] == 0xFE          # SOP2, unacknowledged by default
        assert pkt[2] == 0x02          # DID
        assert pkt[3] == 0x30          # CID
        assert pkt[4] == 0x05          # SEQ
        assert pkt[5] == 0x06          # DLEN = len(data) + 1
        assert pkt[6:11] == bytes([0x64, 0x00, 0x5A, 0x01, 0x00])
        assert len(pkt) == 12

    def test_checksum_covers_did_through_data_only(self):
        pkt = p.build(0x02, 0x30, seq=5, data=bytes([0x64, 0x00, 0x5A, 0x01, 0x00]))
        assert pkt[-1] == p.checksum(pkt[2:-1])

    def test_answer_flag_selects_sop2(self):
        assert p.build(0, 1, answer=True)[1] == 0xFF
        assert p.build(0, 1, answer=False)[1] == 0xFE

    def test_dlen_is_data_length_plus_one(self):
        for n in range(0, 32):
            assert p.build(0x02, 0x01, data=bytes(n))[5] == n + 1

    def test_rejects_out_of_range_seq(self):
        with pytest.raises(ValueError):
            p.build(0x02, 0x01, seq=256)


class TestDriveEncoders:
    def test_roll_golden_vector(self):
        # speed=100 (0x64), heading=90 (0x005A), mode=GO(1), reserved=0
        assert p.roll(100, 90, seq=5).hex() == "fffe023005066400 5a0100 03".replace(" ", "")

    def test_roll_clamps_speed(self):
        assert p.roll(999, 0)[6] == 255
        assert p.roll(-50, 0)[6] == 0

    def test_roll_wraps_heading(self):
        assert p.roll(0, 370)[7:9] == (10).to_bytes(2, "big")
        assert p.roll(0, -10)[7:9] == (350).to_bytes(2, "big")

    def test_stop_uses_mode_zero_and_zero_speed(self):
        pkt = p.stop(seq=6)
        assert pkt[6] == 0                       # speed
        assert pkt[9] == p.RollMode.STOP

    def test_calibrate_uses_mode_two_and_does_not_drive(self):
        """ROLL mode 2 rotates the heading reference without driving (UC4)."""
        pkt = p.calibrate(180, seq=1)
        assert pkt[6] == 0                       # speed must be zero
        assert pkt[9] == p.RollMode.CALIBRATE
        assert pkt[7:9] == (180).to_bytes(2, "big")

    def test_set_heading_golden_vector(self):
        assert p.set_heading(0, seq=7).hex() == "fffe02010703 0000 f2".replace(" ", "")


class TestLedAndSafety:
    def test_main_led_golden_vector(self):
        assert p.set_main_led(255, 0, 0, seq=8).hex() == "fffe02200804 ff0000 d2".replace(" ", "")

    def test_main_led_clamps(self):
        pkt = p.set_main_led(300, -5, 128)
        assert pkt[6:9] == bytes([255, 0, 128])

    def test_motion_timeout_is_big_endian_u16(self):
        pkt = p.set_motion_timeout(2000)
        assert pkt[6:8] == (2000).to_bytes(2, "big")

    def test_ping_requests_an_answer(self):
        """PING is the readiness gate (UC1), so it must be acknowledged."""
        assert p.ping(seq=9)[1] == 0xFF
        assert p.ping(seq=9).hex() == "ffff00010901f4"

    def test_drive_commands_are_unacknowledged(self):
        """The hot path must never block on a reply (N1/N3)."""
        for pkt in (p.roll(100, 90), p.stop(), p.calibrate(90), p.set_main_led(1, 2, 3)):
            assert pkt[1] == 0xFE


class TestDecoder:
    def _response(self, code=0x00, seq=0x05, data=b""):
        body = bytes([code, seq, len(data) + 1]) + data
        return bytes([0xFF, 0xFF]) + body + bytes([p.checksum(body)])

    def _async(self, id_code=0x03, data=b"\x01\x02"):
        dlen = len(data) + 1
        body = bytes([id_code, dlen >> 8, dlen & 0xFF]) + data
        return bytes([0xFF, 0xFE]) + body + bytes([p.checksum(body)])

    def test_decodes_simple_response(self):
        got = list(p.Decoder().feed(self._response(seq=0x05)))
        assert len(got) == 1 and isinstance(got[0], p.Response)
        assert got[0].seq == 0x05 and got[0].ok

    def test_decodes_async_message_with_two_byte_length(self):
        got = list(p.Decoder().feed(self._async(0x07, b"\xaa\xbb")))
        assert len(got) == 1 and isinstance(got[0], p.AsyncMessage)
        assert got[0].id_code == 0x07 and got[0].data == b"\xaa\xbb"

    def test_reassembles_across_fragments(self):
        """BLE delivers arbitrary fragments; nothing may be lost at a boundary."""
        frame = self._response(seq=0x11, data=b"\x01\x02\x03")
        d = p.Decoder()
        out = []
        for i in range(len(frame)):          # one byte at a time, worst case
            out += list(d.feed(frame[i : i + 1]))
        assert len(out) == 1 and out[0].seq == 0x11

    def test_decodes_two_frames_in_one_chunk(self):
        d = p.Decoder()
        got = list(d.feed(self._response(seq=1) + self._async(0x03)))
        assert len(got) == 2
        assert isinstance(got[0], p.Response) and isinstance(got[1], p.AsyncMessage)

    def test_demultiplexes_interleaved_sync_and_async(self):
        """Async sensor data arrives interleaved with command replies (A7)."""
        d = p.Decoder()
        stream = self._async(0x03) + self._response(seq=2) + self._async(0x07)
        kinds = [type(m).__name__ for m in d.feed(stream)]
        assert kinds == ["AsyncMessage", "Response", "AsyncMessage"]

    def test_resynchronises_after_leading_garbage(self):
        d = p.Decoder()
        got = list(d.feed(b"\x00\x11\x22" + self._response(seq=9)))
        assert len(got) == 1 and got[0].seq == 9

    def test_partial_frame_yields_nothing_and_waits(self):
        d = p.Decoder()
        frame = self._response(seq=3, data=b"\x01\x02\x03")
        assert list(d.feed(frame[:4])) == []
        assert len(list(d.feed(frame[4:]))) == 1

    def test_error_response_is_not_ok(self):
        got = list(p.Decoder().feed(self._response(code=p.ResponseCode.INVALID_PARAMETER)))
        assert not got[0].ok

    def test_never_raises_on_arbitrary_bytes(self):
        """A malformed stream must not kill the notify pump (A7)."""
        import random
        random.seed(0)
        d = p.Decoder()
        for _ in range(200):
            list(d.feed(bytes(random.randrange(256) for _ in range(16))))


class TestPortability:
    def test_module_imports_only_stdlib(self):
        """N8: the codec must carry no I/O or platform dependency, so it ports
        to Swift as a transcription. Checked against the import graph rather
        than the source text -- prose in docstrings is not a dependency."""
        import ast
        import inspect

        tree = ast.parse(inspect.getsource(p))
        imported = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                imported.update(a.name.split(".")[0] for a in node.names)
            elif isinstance(node, ast.ImportFrom) and node.module:
                imported.add(node.module.split(".")[0])

        allowed = {"__future__", "dataclasses", "enum", "typing"}
        assert imported <= allowed, f"non-stdlib or I/O imports leaked in: {imported - allowed}"


class TestSensorStreamingRate:
    """The streaming parameter is a divisor of a 400 Hz clock, NOT a period.

    Verified on hardware: divisor 100 -> 4.01 Hz, 50 -> 8.01 Hz, 25 -> 15.96 Hz,
    all within 0.25% of 400/divisor. Reading it as milliseconds understates the
    rate by 25x and makes a healthy stream look like 60% packet loss.
    """

    def test_divisor_to_hz_matches_hardware_measurements(self):
        assert p.divisor_to_hz(100) == pytest.approx(4.0)
        assert p.divisor_to_hz(50) == pytest.approx(8.0)
        assert p.divisor_to_hz(25) == pytest.approx(16.0)

    def test_hz_to_divisor_round_trips(self):
        for hz in (1.0, 4.0, 8.0, 16.0, 20.0, 50.0):
            assert p.divisor_to_hz(p.hz_to_divisor(hz)) == pytest.approx(hz, rel=0.05)

    def test_divisor_is_never_zero(self):
        """Zero would mean 'stop streaming', not 'stream fast'."""
        assert p.hz_to_divisor(10_000) >= 1

    def test_divisor_fits_the_u16_field(self):
        assert p.hz_to_divisor(0.001) <= 0xFFFF

    def test_divisor_is_encoded_as_the_first_data_word(self):
        pkt = p.set_data_streaming(divisor=25, samples_per_packet=1, mask=0x10000, seq=1)
        assert pkt[6:8] == (25).to_bytes(2, "big")

    def test_streaming_command_is_acknowledged(self):
        """Setup command -- worth knowing whether the droid accepted it."""
        assert p.set_data_streaming(divisor=100, samples_per_packet=1, mask=1)[1] == 0xFF

    def test_zero_mask_stops_the_stream(self):
        pkt = p.set_data_streaming(divisor=0, samples_per_packet=0, mask=0)
        assert pkt[10:14] == bytes(4)
