import XCTest
@testable import BB8Kit

/// Cross-implementation contract tests.
///
/// `bb8_vectors.json` is generated by the Python implementation
/// (`bb8ctl vectors`). If these pass, the Swift codec and the Python codec
/// produce identical bytes for identical inputs — which is the entire point of
/// having built the Python tool first.
///
/// A divergence here means the iOS app would talk subtly different protocol
/// from the one actually verified against hardware.
final class GoldenVectorTests: XCTestCase {

    private struct Vectors: Decodable {
        let handshake: [Handshake]
        let characteristics: [String: String]
        let packets: [String: String]
        let sensorMasks: SensorMasks

        struct Handshake: Decodable { let uuid: String; let hex: String }
        struct SensorMasks: Decodable {
            let drivePreset: [String]
            let primary: UInt32
            let extended: UInt32
            let fieldOrder: [String]

            enum CodingKeys: String, CodingKey {
                case drivePreset = "drive_preset"
                case primary, extended
                case fieldOrder = "field_order"
            }
        }

        enum CodingKeys: String, CodingKey {
            case handshake, characteristics, packets
            case sensorMasks = "sensor_masks"
        }
    }

    private var vectors: Vectors!

    override func setUpWithError() throws {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "bb8_vectors", withExtension: "json"),
            "golden vectors missing from the test bundle"
        )
        vectors = try JSONDecoder().decode(Vectors.self, from: Data(contentsOf: url))
    }

    private func expect(_ name: String, _ produced: Data, file: StaticString = #filePath, line: UInt = #line) throws {
        let want = try XCTUnwrap(vectors.packets[name], "no vector named \(name)")
        XCTAssertEqual(produced.hexString, want, "\(name) diverges from the Python codec",
                       file: file, line: line)
    }

    // MARK: - Packets

    func testRoll() throws {
        try expect("roll_100_90", Sphero.roll(speed: 100, heading: 90, seq: 5))
        try expect("roll_full_0", Sphero.roll(speed: 255, heading: 0, seq: 0))
    }

    func testStop() throws {
        try expect("stop", Sphero.stop(seq: 6))
    }

    /// Aim mode depends entirely on this one.
    func testCalibrate() throws {
        try expect("calibrate_180", Sphero.calibrate(heading: 180, seq: 1))
    }

    func testSetHeading() throws {
        try expect("set_heading_0", Sphero.setHeading(0, seq: 7))
    }

    func testLEDs() throws {
        try expect("main_led_red", Sphero.setMainLED(red: 255, green: 0, blue: 0, seq: 8))
        try expect("back_led_full", Sphero.setBackLED(brightness: 255, seq: 2))
    }

    /// The dead-man switch. If this diverges, the droid does not stop itself.
    func testMotionTimeout() throws {
        try expect("motion_timeout_2000", Sphero.setMotionTimeout(milliseconds: 2000, seq: 3))
    }

    /// Without stabilization the control system stays off and roll is inert.
    func testStabilization() throws {
        try expect("stabilization_on", Sphero.setStabilization(true, seq: 4))
    }

    func testAcknowledgedCommands() throws {
        try expect("ping", Sphero.ping(seq: 9))
        try expect("power_state", Sphero.getPowerState(seq: 10))
    }

    // MARK: - BLE topology

    func testCharacteristicUUIDsMatch() throws {
        XCTAssertEqual(vectors.characteristics["command"], Sphero.commandCharacteristic)
        XCTAssertEqual(vectors.characteristics["response"], Sphero.responseCharacteristic)
        XCTAssertEqual(vectors.characteristics["wake"], Sphero.wakeCharacteristic)
        XCTAssertEqual(vectors.characteristics["anti_dos"], Sphero.antiDOSCharacteristic)
        XCTAssertEqual(vectors.characteristics["tx_power"], Sphero.txPowerCharacteristic)
    }

    /// Order matters as much as content: writing these in the wrong sequence
    /// leaves the droid connected and permanently mute.
    func testHandshakeMatchesInContentAndOrder() throws {
        XCTAssertEqual(Sphero.handshake.count, vectors.handshake.count)
        for (mine, theirs) in zip(Sphero.handshake, vectors.handshake) {
            XCTAssertEqual(mine.uuid, theirs.uuid)
            XCTAssertEqual(mine.payload.hexString, theirs.hex)
        }
    }

    // MARK: - Sensors

    /// The wire carries no field tags, so a layout mismatch decodes every
    /// sensor as its neighbour — plausible numbers, all wrong.
    func testSensorMasksAndFieldOrderMatch() throws {
        // Python uses snake_case names, Swift camelCase. The mapping is spelled
        // out rather than derived, so a rename on either side fails loudly here
        // instead of silently reordering the decode.
        let pythonToSwift = [
            "yaw": "yaw", "speed": "speed",
            "locator_x": "locatorX", "locator_y": "locatorY",
            "velocity_x": "velocityX", "velocity_y": "velocityY",
        ]
        let names = vectors.sensorMasks.drivePreset.map { pythonToSwift[$0] ?? $0 }
        XCTAssertEqual(Set(names), Set(SpheroSensors.drivePreset))

        let (primary, extended) = try SpheroSensors.masks(for: SpheroSensors.drivePreset)
        XCTAssertEqual(primary, vectors.sensorMasks.primary)
        XCTAssertEqual(extended, vectors.sensorMasks.extended)

        let mine = SpheroSensors.layout(primary: primary, extended: extended).map(\.name)
        let theirs = vectors.sensorMasks.fieldOrder.map { pythonToSwift[$0] ?? $0 }
        XCTAssertEqual(mine, theirs, "field order diverges — decoded values would be shifted")
    }
}

extension Data {
    var hexString: String { map { String(format: "%02x", $0) }.joined() }
}
